const visitedCountries = [
    'Argentina',
    'Australia',
    'Belgium',
    'Brazil',
    'Canada',
    'Colombia',
    'Croatia',
    'Cuba',
    'Czech Republic',
    'Denmark',
    'Egypt',
    'France',
    'Germany',
    'Greece',
    'Hong Kong',
    'Hungary',
    'India',
    'Indonesia',
    'Ireland',
    'Italy',
    'Laos',
    'Malaysia',
    'Mexico',
    'Monaco',
    'Nepal',
    'Netherlands',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Singapore',
    'Spain',
    'Sri Lanka',
    'Sweden',
    'Taiwan',
    'Thailand',
    'Turkey',
    'United Kingdom',
    'United States of America',
    'Vietnam',
];

export default visitedCountries;
