name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Match the Node version your app requires

      # 3. Install Dependencies
      - name: Install dependencies
        run: npm install

      # # 4. Run Tests
      # - name: Run tests
      #   run: npm test

      # # 5. Lint and Format Code
      # - name: Run ESLint
      #   run: npm run lint

      # 6. Build the Application
      - name: Build Next.js app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      # 1. Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # 3. Install Dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the Application
      - name: Build Next.js app
        run: npm run build

      # 5. Deploy to AWS Amplify
      - name: Deploy to Amplify
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-2"
        run:
          npx amplify publish --yes

          # 6. Deploy to S3 (Optional for static assets)
      - name: Sync assets to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./public s3://alex-perez-davies-blog --region eu-west-2
