name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Install AWS CLI and Amplify CLI
        run: |
          npm install -g aws-cli @aws-amplify/cli

      - name: Deploy to AWS Amplify
        run: |
          # Replace 'YourAppName' with your actual Amplify app name
          APP_ID=$(aws amplify list-apps --query "apps[?name=='YourAppName'].appId" --output text)

          if [ -z "$APP_ID" ]; then
            echo "Amplify app not found. Please create the app in AWS Amplify console first."
            exit 1
          fi

          # Create a new branch deployment
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/\//_/g')

          # Deploy the branch
          DEPLOYMENT_ID=$(aws amplify create-deployment \
            --app-id $APP_ID \
            --branch-name $BRANCH_NAME \
            --query "jobId" \
            --output text)

          echo "Deployment initiated with ID: $DEPLOYMENT_ID"

          # Wait for deployment to complete
          aws amplify wait deployment-complete \
            --app-id $APP_ID \
            --job-id $DEPLOYMENT_ID

      - name: Sync assets to S3
        run: |
          aws s3 sync ./public s3://alex-perez-davies-blog --region eu-west-2
